### ISSUE TITLE
Add cotire

### ISSUE THREAD

**Issue by pfultz2** [RadeonOpenCompute/rocm-cmake#2]
This can help speed up building in many targets.

**Comment by icarus-sparry** [comment]
At least a reference to where to find cotire would help, e.g. [cotire](https://github.com/sakra/cotire)

According to the page.

    The functionality provided by cotire has been superseded by features added to CMake 3.16. Support for pre-compiling and 
    unity builds is now built into CMake. Thus, there will not be any further updates or support for this project.
