### ISSUE TITLE
Possibility of INSTALL_PREFIX ?

### ISSUE THREAD

**Issue by baerbock** [RadeonOpenCompute/rocm-cmake#5]
I've failed to use `cmake -DCMAKE_INSTALL_PREFIX=$pkgdir/opt/rocm --build . --target install`

to package rocm-cmake for my distro. How to correctly use it?

**Comment by pfultz2** [comment]
The install prefix must be set during the configure stage:

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$pkgdir/opt/rocm ..
cmake --build . --target install
```
