### ISSUE TITLE
Incorrect tests

### ISSUE THREAD

**Issue by icarus-sparry** [RadeonOpenCompute/rocm-cmake#55]
https://github.com/RadeonOpenCompute/rocm-cmake/blob/48121ade0e70b89d393112642d8f394289fe680f/share/rocm/cmake/ROCMCreatePackage.cmake#L20

Using
           if(${inout_variable})
where the value of inout_variable might be CPACK_DEB_WIBBLE looks up the truthfulness of the variable CPACK_DEB_WIBBLE.
However the cmake idea of true does not include strings like
      N
      0
      FALSE
so this function givens incorrect results for

set(X FALSE)
rocm_join_if_set("," X "he said")

the function ought to be fixed to compare to the empty string or else renamed to rocm_join_if_true to reflect its nature. Of course the latter function is much less useful.

**Comment by lawruble13** [comment]
Resolved by #59.
