### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by kiritigowda** [RadeonOpenCompute/rocm-cmake#6]
Can this project have a release for the stable version that could be used and linked to another project?

**Comment by saadrahim** [comment]
Hi Kiriti, rocm-cmake has releases tagged. Is that what you were looking for?

**Comment by kiritigowda** [comment]
@saadrahim yes, the latest tag would be good. I think when I opened this issue there were no tags. Maybe I can use the latest tag available now. I can close this issue.
