### ISSUE TITLE
circular symlink issue: link <package>/lib/lib<package>.so to /opt/rocm/lib/lib<package>.so

### ISSUE THREAD

**Issue by yhmtsai** [RadeonOpenCompute/rocm-cmake#86]
https://github.com/RadeonOpenCompute/rocm-cmake/blob/bd4e360c73fa366f817f5aa013433e799d8cd659/share/rocm/cmake/ROCMInstallTargets.cmake#L175-L177

The symlink seems to be wrong. 
It creates the symlink in package library with link-destination `/opt/rocm/lib/..` and overwrites the original library file. The library also creates symlink in /opt/rocm/lib/ in reversed way.

Use hipFFT as example,
`\${LINK_PATH}/$<TARGET_LINKER_FILE_NAME:${TARGET}>`  is `../../lib/libhipfft.so`
`\${LINK_DIR}/${ROCM_INSTALL_LIBDIR}/$<TARGET_LINKER_FILE_NAME:${TARGET}>`  is  `/opt/rocm/hipfft/lib/libhipfft.so`
`/opt/rocm/hipfft/lib/libhipfft.so` -> `../../lib/libhipfft.so` (i.e. `/opt/rocm/lib/libhipfft.so`)
It overwrites the original library.
and hipFFT also creates `/opt/rocm/lib/libhipfft.so` -> `/opt/rocm/hipfft/lib/libhipfft.so` to lead circular symlink

**Comment by lawruble13** [comment]
This issue potentially arises when the library uses `rocm_install_symlink_subdir`, which is done in all math libraries in ROCm 5.1. That said, I am also having difficulty reproducing the issue. @yhmtsai, can you confirm that this is an issue you actually encountered (as opposed to a theoretical issue)? If so, can you provide some additional information on how to reproduce the issue (e.g. a specific library & version, the commands used, environment)?
