### ISSUE TITLE
Error installing rocm-cmake

### ISSUE THREAD

**Issue by JBBIntel** [RadeonOpenCompute/rocm-cmake#98]
I am trying to install rocm-cmake on Ubuntu 20.04. I am getting the following error;

:~/rocm-cmake/build$ cmake --build . --target install
Install the project...
-- Install configuration: ""
-- Up-to-date: /opt/rocm/./share
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot set permissions on "/opt/rocm/./share": Operation not
  permitted.

make: *** [Makefile:119: install] Error 1

**Comment by cgmb** [comment]
`/opt` is typically owned by root. The instructions in rocm-cmake's README should probably say `sudo cmake --build . --target install`

**Comment by cgmb** [comment]
I believe your problem will be resolved by using `sudo cmake --build . --target install` and have updated the documentation accordingly. If that does not fix the error you're seeing, please feel free to reopen.
